name: publish-to-microsoft-store

on:
  push:
    branches: ["master" ]
  pull_request:
    branches: ["master"]

jobs:

  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    # Create the app package by building and packaging the Windows Application Packaging project
    - name: Create the app package
      shell: pwsh
      run: |
        .\build.ps1
        
    # Upload the MSIX package to Windows Store
    - uses: isaacrlevin/windows-store-action@1.0
      name: Publish to Store
      with:
        tenant-id: ${{ secrets.AZURE_AD_TENANT_ID }}
        client-id: ${{ secrets.AZURE_AD_APPLICATION_CLIENT_ID }}
        client-secret: ${{ secrets.AZURE_AD_APPLICATION_SECRET }}
        app-id: ${{ secrets.STORE_APP_ID }}
        package-path: ".\\AppPackages"